### ISSUE TITLE
Add TicketMaster::Provider::Base::User

### ISSUE THREAD

**Issue by zedtux** [hybridgroup/taskmapper#15] opened 2011-05-23 17:16 UTC
When I was using ticketmaster-github, after retrieved a ticket of a project, I wasn't able to get the ticket author details.

It may be useful to implement it, isn't it?

**Comment by cored** [comment] 2011-05-23 17:46
Sure thing zedtux, this will be fix soon. Thanks for the report. The only thing is that this is not a bug related to ticketmaster itself, is related to ticketmaster-github. Please reopen the ticket for that project, I'll close this one.

**Closed as completed** 2011-05-23 17:47 UTC

**Comment by zedtux** [comment] 2011-05-24 06:15
It seems to related to all sub modules of ticketmaster.
I can't see how to retrieve a user with ticketmaster-pivotal, same for ticketmaster-lighthouse etc...

Maybe I didn't explain clearly what I'm requesting.
So, yes it's not a bug but a feature request:
The idea is to be able todo something like:

```
pivotal = TicketMaster.new(:pivotal, {:username => "john", :password => "seekrit"})
project = pivotal.project["testproject"]
project.owner.name
#=> zedtux
project.owner.email
#=> zedtux@zedroot.org
```

etc...

**Comment by cored** [comment] 2011-05-24 12:19
Hi zedtux,

Well as far as I see it this is not the intended public API of ticketmaster,
but it could be a good feature of course. Will check it out.

Thanks for the request and for using ticketmaster.

On Tue, May 24, 2011 at 2:15 AM, zedtux <
reply@reply.github.com>wrote:

> It seems to related to all sub modules of ticketmaster.
> I can't see how to retrieve a user with ticketmaster-pivotal, same for
> ticketmaster-lighthouse etc...
> 
> Maybe I didn't explain clearly what I'm requesting.
> So, yes it's not a bug but a feature request:
> The idea is to be able todo something like:
> 
>    pivotal = TicketMaster.new(:pivotal, {:username => "john", :password =>
> "seekrit"})
>    project = pivotal.project["testproject"]
>    project.owner.name
>    #=> zedtux
>    project.owner.email
>    #=> zedtux@zedroot.org
> 
> etc...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hybridgroup/ticketmaster/issues/15#comment_1226326

## 

Rafael George

**Comment by zedtux** [comment] 2011-05-24 15:02
Thanks to you for your quick answers ;)
